INSERT INTO ALUNO (nome) VALUES ('Aluno 01');
INSERT INTO ALUNO (nome) VALUES ('Aluno 02');
INSERT INTO ALUNO (nome) VALUES ('Aluno 03');
INSERT INTO ALUNO (nome) VALUES ('Aluno 04');
INSERT INTO ALUNO (nome) VALUES ('Aluno 05');

INSERT INTO CURSO (nome) VALUES ('Curso 01');
INSERT INTO CURSO (nome) VALUES ('Curso 02');
INSERT INTO CURSO (nome) VALUES ('Curso 03');
INSERT INTO CURSO (nome) VALUES ('Curso 04');
INSERT INTO CURSO (nome) VALUES ('Curso 05');